Changes to enable mutt mode: Please set your mutt's editor to 'vp' (under ~/.vim/bundle/VimPyServer); any write on the file will automatically update mutt.

diff --git a/bin/vp b/bin/vp
--- a/bin/vp
+++ b/bin/vp
@@ -27,23 +27,30 @@ function openFile () {
     vim "$FILE_ESCAPED"
   fi
 }
+function waitMode () {
+    printf "VimPyServer in mutt mode.\n"
+    printf "%s\n" "let g:vimperatorVimPyServer=$SERVERPORT" |nc $SERVERHOST $SERVERPORT
+    openFile "$1"
+    # Repaint vim
+    printf "%s\n" "edit" | nc $SERVERHOST $SERVERPORT
+    # wait for ANY buffer write, then terminate 
+    printf "\n%s\n" "Wait for end of wait-mode..."
+    nc -l  $CLIENTPORT
+}
 
 # Open several files on a single VimPyServer instance
 if [ $# -gt 0 ]; then
   # printf  "Number or arguments: %i\n" $#
-  if [ "$1" = "-vimperator" ] && [ $# != 2 ]; then
-    printf "ERROR. vp with -vimperator requires one file argument.\n" 1>&2
+  if [ "$1" = "-wait" ] && [ $# != 2 ]; then
+    printf "ERROR. vp with -wait requires one file argument.\n" 1>&2
     exit 1
   fi
-  if [ "$1" = "-vimperator" ] && [ $# = 2 ]; then
-    printf "VimPyServer in vimperator mode.\n"
-    printf "%s\n" "let g:vimperatorVimPyServer=1" |nc $SERVERHOST $SERVERPORT
-    openFile "$2"
-    # Repaint vim
-    printf "%s\n" "edit" | nc $SERVERHOST $SERVERPORT
-    # wait for ANY buffer write, then terminate 
-    printf "\n%s\n" "Wait for end of vimperator-mode..."
-    nc -l  $CLIENTPORT
+  BASENAME=$(basename "$1")
+  echo $BASENAME
+  if [[ "$BASENAME" = mutt-* ]]; then 
+    waitMode "$1"
+  elif [ "$1" = "-wait" ] && [ $# = 2 ]; then
+    waitMode "$2"
   else
     printf "VimPyServer in multifile mode.\n"
     for f in "$@"; do
